### ISSUE TITLE
Abuse protection

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#10]
Reasoning
- In public play you have people abuse anything possible
- Spamming is one thing
- Problematic wording another
- Could be also links (if you can open them via the logs)
- ASCII art

Considerations
- Probably needs a good amount of brainstorming, discussion and research for the right scope and meaningful approach
- Ability to mute people/groups/side would be a sub-feature
- Possibly admin options would be another

**Comment by ConnorAU** [comment]
For now I think it is realistic to do the following tasks. I'll mark them off as I go.
- [x] Word/Phrase filter (blacklist) dff9c6bc89bc99bcb629b58a581381f5a4409d77 
- [x] URL filter (whitelist, so links for specified domains can be clicked in the history viewer) 22626224bbff89486c237f3dce36dc7b906f9116
- [x] Player muting (persistent across sessions) fc8898d11ec487532c037de520a93ca623894336

**Comment by ConnorAU** [comment]
dff9c6bc89bc99bcb629b58a581381f5a4409d77 Word/Phrase filter (blacklist)
