### ISSUE TITLE
Admin/Moderator and Support chat

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#11]
Reasoning
- Could be useful to help administrate big servers
- If global chat is disabled, and you need assistance

Considerations
- Admin/Moderator and Support could be two different ones (first a special group to allow have them chat easily among each other)

**Comment by ConnorAU** [comment]
You can achieve this using custom channels. If you want an admin only chat that is not using custom channels I feel it would be very difficult to implement, and maybe outside the scope of this mod.

**Comment by kju** [comment]
The idea here is to have such feature available out of the box for the whole server (aka not mission/game mode specific) and no extra mods.

Configuration should be server side (ie to define additional admins by steam id).

**Comment by ConnorAU** [comment]
I feel this falls outside the scope of the mod. Will continue to discuss this on discord.
