### ISSUE TITLE
Show Normal Chat Inputs

### ISSUE THREAD

**Issue by Kazblack180** [ConnorAU/A3ExtendedChat#12]
If you send a message with Rcon it dosnt show up. There no feedback for commands like #login. It would be nice if yould could fix that.

**Comment by ConnorAU** [comment]
Currently this is not possible as there is no way to detect system messages. I have requested a solution for this which currently exists on the a3 dev branch, but it doesn't work properly so I have to wait for it to be fixed and then released to the a3 public branch before I can implement it.

https://feedback.bistudio.com/T150854
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#HandleChatMessage

**Comment by ConnorAU** [comment]
Done https://github.com/ConnorAU/A3ExtendedChat/releases/tag/v2.0
