### ISSUE TITLE
Feature Request – Appearance Personalization

### ISSUE THREAD

**Issue by Quailsnap** [ConnorAU/A3ExtendedChat#2]
A3ExtendedChat would be well-served with more customization options in the settings menu. Stuff like:
- typeface
- font size
- font color
- background color/presence

**Comment by ConnorAU** [comment]
I am going to get onto this, just need to complete this issue on another mod to add colour picking functionality in the way I want it

https://github.com/ConnorAU/A3UserInputMenus/issues/1

**Comment by ConnorAU** [comment]
https://github.com/ConnorAU/A3ExtendedChat/commit/1017adc110dcf9cf50f724512d7ceea7121b9f08
