### ISSUE TITLE
License

### ISSUE THREAD

**Issue by VileAce** [ConnorAU/A3ExtendedChat#3]
In your license.txt it indicates 2. You are not permitted to:  a. Modify the material.  By this are you saying that I can not edit for example 'fn_commonTask.sqf' to change colors.

**Comment by ConnorAU** [comment]
I am happy to discuss an exception for you/your server. Just send me the details.

**Comment by VileAce** [comment]
Thank you for the reply.  Your script is well made and has a lot of nice features.  Unfortunately,  it is missing a couple of features that we can not live without so we will not be using the script at this time.
