### ISSUE TITLE
Chat separation (player messages, kill messages, status messages) into multiple panels

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#4]
Reasoning:
1. The mix of different types makes chat is very messy
2. An admin may need status messages
3. Players may need status messages when friends have issues joining
4. You want to have a clean(er) interface

Considerations:
- Positioning is not easy. Maybe bottom left chat, center left status and top left kill messages. Still difficult to make work with the customization.
- Customization for all? Customization separate for each or all the same?
- Different defaults? Like 3-5 lines for status, 5 for kills and 10 for chat?

**Comment by ConnorAU** [comment]
My main concern with this is some displays (especially lower resolution/aspect radios) wouldn't have enough free space to display 3 different feeds. It may make the mod annoying to use with other hud modifications.

**Comment by ConnorAU** [comment]
I feel this falls a little outside the scope of the mod. Will continue to discuss this on discord.
