### ISSUE TITLE
Active streamer mode to hit chat panel(s) by default

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#6]
Reasoning:
- You may not want to expose your current server

Considering:
- Needs a way to active/toggle if you want it show regardless
- May need a hint (in chat) to make people aware of the functionality

**Comment by ConnorAU** [comment]
Not sure I understand. Are you saying you want to hide the chat feed automatically when you join a server until you unhide it? Is this to hide motd messages (for example)?

**Comment by kju** [comment]
https://community.bistudio.com/wiki/isStreamFriendlyUIEnabled

if this is active, you want to hide information that gives away the server you are on (aka chat, kill messages and motd, etc)
and yes ability to unhide it would be good to have

**Comment by ConnorAU** [comment]
ok, so I will set up hidden by default when streamer mode is enabled, and maybe a toggle for it, which I'll make in conjunction with https://github.com/ConnorAU/A3ExtendedChat/issues/5

**Comment by ConnorAU** [comment]
5f3250ab1fba56ed24d3ce545b06249066eb3c4f
