### ISSUE TITLE
Ability to tag people or custom groups like in discord

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#7]
Reasoning:
- You may want to highlight a message to a specific person or custom group (ie admins, or fireteams)

Considerations:
- The tag probably should be just a different chat message background - if it gets too prominent, it may get annoying or distracting (and abused)
- Needs a way to define the custom groups
- (LoggedIn/Voted) Admin could be a default
- Would be good to support multiple admins/moderators

**Comment by ConnorAU** [comment]
Done (for players) https://github.com/ConnorAU/A3ExtendedChat/releases/tag/v2.0
