### ISSUE TITLE
Ability to whisper people or custom groups like in discord

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#8]
Reasoning:
- You may want to send a message to a specific person or custom group (ie admins, or fireteams)

Considerations:
- The whisper may get a different chat message background to make it stand out - otherwise it may get too prominent, it may get annoying or distracting (and abused)
- Needs a way to define the custom groups
- (LoggedIn/Voted) Admin could be a default
- Would be good to support multiple admins/moderators

**Comment by ConnorAU** [comment]
704529670ea1477100674846d23920c923588fdc
