### ISSUE TITLE
Ability to activate timestamps in chat display

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3ExtendedChat#9]
Reasoning
- Not sure if actually necessary but came up in our discussion
- Could be useful to have for specific situations

Considerations
- Should be disabled by default
- Might be useful be able to switch between:
-- XX seconds/minutes ago
-- Ingame time
-- Realtime (Dedmen wants to implement that)
(also for the logs and external tools like RCON)

**Comment by ConnorAU** [comment]
Would adding the different formats to the history menu be enough? not sure it would be useful in the chat feed itself because you can only see current messages, no history.

**Comment by kju** [comment]
sounds fine

**Comment by ConnorAU** [comment]
Done https://github.com/ConnorAU/A3ExtendedChat/releases/tag/v2.0
